[package]
name = "evdev_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-colorizer = "1"
evdev = "0"
actix-web = "3"
serde = "1"
serde_json = "1"
